### PR TITLE
Feat: "drop only" dndzones

### PR DESCRIPTION
**Pull request by eduardomartines**
# Motivation
I needed a zone that was only dropable so I created a dropOnly attribute in dndzone;

I think its also somehow related to things like that https://github.com/isaacHagoel/svelte-dnd-action/issues/403

Any thoughts on that? Like a better way to accomplish this?

Thank you for your time!

### CODE REVIEW

**Comment by isaacHagoel** [comment]
what is the difference between this and the existing `dragDisabled` prop?

**Comment by eduardomartines** [comment]
> what is the difference between this and the existing `dragDisabled` prop?

with `dragDisabled` the `items` is required, `dropOnly` assumes the zone is just a simple "bucket".

**Comment by isaacHagoel** [comment]
But items can be empty (an empty list)

**Comment by eduardomartines** [comment]
`items` with an empty array cause errors to start popping out:

1. "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')"
2. "Uncaught TypeError: Cannot read properties of undefined (reading 'isDndShadowItem')"

**Comment by isaacHagoel** [comment]
that would be a bug. I just tried it now with one of the examples and it
worked. can u share an example in which an empty list causes issues?

**Comment by eduardomartines** [comment]
Sure, I gonna isolate this in a REPL over the weekend

**Pull request closed without merging**
