### PR TITLE
Feature: handle

### PR DESCRIPTION
**Pull request by dilonhenrique**
A simples handler selector option to enable this very requested feature.

### CODE REVIEW

**Comment by isaacHagoel** [comment]
Hi, can you please provide some more info about this feature? what is the problem we are trying to solve?

**Comment by dilonhenrique** [comment]
It's a Drang handle: the drag only start by a nested element rather than the entire draggable element.
It's kind like the current solution in the examples, but less like a workaround and more like a feature.

If this feature impacts other features or if I missed something important, please let me know and I'll fix it as soon as possible.

**Comment by isaacHagoel** [comment]
how is it used? can you update the README and/or provide an example? will it survive people passing in a different handle dynamically? how is keyboard dragging and accessibility features affected?
I remember I played with an idea like this (my plan was to have the user mark the handle using a data attribute) and hit some issues. Not sure if this implementation will have the same problems.

**Comment by dilonhenrique** [comment]
Unfortunately I will not be able to review all the items mentioned. What
can I do:
 - write a code example;
 - keyboard action was not changed;
 - review accessibility functions.

What I can't do:
 - change the README;
 - test different handle dynamically (dont quite understand).

If you can specify the problems you had when trying to implement a similar
solution, it would be greatly appreciated. This way I can review these
details.

As soon as I have news, I'll post it here.

Em sáb., 27 de abr. de 2024 00:42, Isaac Hagoel ***@***.***>
escreveu:

**Comment by isaacHagoel** [comment]
Not sure where you are with this but [this comment](https://github.com/isaacHagoel/svelte-dnd-action/issues/509#issuecomment-2113447474) might be relevant

**Comment by isaacHagoel** [comment]
@dilonhenrique I created #576  for drag handle support. Not planning to merge it until tomorrow. Just FYI

**Comment by dilonhenrique** [comment]
@isaacHagoel , thanks for let me know. Unfortunately I didn't had the time to move forward and besides that, the solution I sent fulfilled my needs.

I saw you made significantly more changes than I did, so I presume that was more complex that I thought. Thanks for the effort put on it.

**Comment by isaacHagoel** [comment]
Got it. I merged #576 so closing this one. Thanks for the effort and discussion!

**Pull request closed without merging**
