### PR TITLE
feat: optional zone item tabindex

### LINKED ISSUE #460: Remove tabindex of DndZone items
I was wondering if there is a possibility to remove the tabindex of dndzone items. Currently, I've come across an option to set the tabindex of the dndzone container, however, my requirement is slightly different. Would appreciate any guidance you can provide on this matter. Thank you.

### PR DESCRIPTION
**Pull request by gyurielf**
Closes #460

### CODE REVIEW

**Comment by gyurielf** [comment]
@isaacHagoel Could you take a look ?
I've tested and looks good for me.

**Comment by isaacHagoel** [comment]
Overall it looks good. I will need to spend some time testing it.
Can you please bump the version and update the release notes?

**Comment by isaacHagoel** [comment]
Please update to index.d.ts. 
Did you notice that the focusedItem gets its tabIndex set to 0 in two places in the code. 
Shouldn't that come from the config as well?

**Comment by gyurielf** [comment]
> Please update index.d.ts. Did you notice that the focusedItem gets its tabIndex set to 0 in two places in the code? Shouldn't that come from the config as well?

Sorry for the late answer.

It's updated. Or what do you mean, what should I update ?
In my tests it works well.
Can you point in the code there the problem is came from ?

BR.

**Comment by isaacHagoel** [comment]
I meant [here](https://github.com/isaacHagoel/svelte-dnd-action/blob/868520ae57c6145ef5c023bdd8be683d48c7a57f/src/keyboardAction.js#L265) and here(https://github.com/isaacHagoel/svelte-dnd-action/blob/868520ae57c6145ef5c023bdd8be683d48c7a57f/src/keyboardAction.js#L334).
I have been dealing with production issues at work (not dnd related :)) so I didn't have time to test thoroughly yet. I will try to block time tomorrow.

**Comment by isaacHagoel** [comment]
so thinking about this more, I am pretty sure the two zeros I mentioned about should be whatever is configured as well. thoughts?
also, the test case you're using, if it is simple enough, can you make a repl out of it?

**Comment by isaacHagoel** [comment]
FYI, when u have time for this pls pull from master and re-bump the version. thx

**Comment by gyurielf** [comment]
Alright. Thanks! I haven't enough time in the last few days. I'll update the PR at the weekend.

**Comment by gyurielf** [comment]
I didn't manage to complete it, because something came up. I'll update it within the next few days. Thy for patience.

**Comment by isaacHagoel** [comment]
No worries, take your time.

**Comment by isaacHagoel** [comment]
looks good. i will test and merge (assuming no issues) tomorrow or the day after. thanks

**Comment by gyurielf** [comment]
> looks good. i will test and merge (assuming no issues) tomorrow or the day after. thanks

Alright!
Thank you!

**Pull request merged**
