### PR TITLE
306: set selected options to node clone

### LINKED ISSUE #306: <select> looses it's value during drag
Select inside an item looses it's value during drag.

REPL: https://svelte.dev/repl/7b879286ec034cb4a83e1a1bcbf64a81?version=3.24.1

### PR DESCRIPTION
**Pull request by mataslib**
fixes #306

### CODE REVIEW

**Comment by isaacHagoel** [comment]
@mataslib sorry for the long delay. somehow it slipped below my radar :(

**Comment by LeoEricson** [comment]
Any update?

**Comment by LeoEricson** [comment]
@isaacHagoel Any update?

**Comment by isaacHagoel** [comment]
Sorry. Super busy.
On the one hand i want to merge it on the other hand it feels insane that
such a workaround is needed

**Comment by LeoEricson** [comment]
@isaacHagoel That's entirely understandable. However, it would seem that the svelte team has no intention of fixing the root issue, so this fix is needed.

**Comment by isaacHagoel** [comment]
Fair enough. I'll try to allocate some time to this during the weekend

**Comment by isaacHagoel** [comment]
this fix is now available starting in version 0.9.17

**Pull request merged**
