### PR TITLE
Made DndEvent generic, falling back to Item

### PR DESCRIPTION
**Pull request by c00**
Should be backwards compatible.

### CODE REVIEW

**Comment by c00** [comment]
Issue https://github.com/isaacHagoel/svelte-dnd-action/issues/381

**Comment by khaki32** [comment]
Awesome, please merge

**Comment by isaacHagoel** [comment]
Cool. Do you mind bumping the patch version in package.json and updating release-notes.md and README.md if needed?
@c00

**Comment by c00** [comment]
@isaacHagoel Done! Updated the release notes, mentioned it in Readme and bumped the patch version.

**Comment by isaacHagoel** [comment]
fixes #381

**Comment by isaacHagoel** [comment]
merged. thanks!

**Pull request merged**
